---
apiVersion: npmctl.com/v1
kind: DesiredState
schemaVersion: 3
metadata:
  name: workload-a-desired-state
  owner: workload-a
spec:
  proxyHosts:
    - domain_names:
        - minimal.example.com
      forward_host: minimal
      forward_port: 8080
      meta:
        managed_by: npmctl
        owner: workload-a
        resource_id: proxy.minimal
  certificates: []
  accessLists: []
  redirectionHosts: []
  deadHosts: []
  streams: []
  users: []
  settings: []
  dnsRecords: []
  pluginResources: []
  externalCertificates: []
