---
apiVersion: npmctl.com/v1
kind: DesiredState
schemaVersion: 3
metadata:
  name: workload-a-desired-state
  owner: workload-a
spec:
  proxyHosts:
    - domain_names:
        - wildcard-app.example.com
      forward_host: app
      forward_port: 3000
      certificate_ref: cert.wildcard-example
      ssl_forced: 1
      meta:
        managed_by: npmctl
        owner: workload-a
        resource_id: proxy.wildcard-app
  certificates:
    - name: wildcard-example
      domain_names:
        - '*.example.com'
        - example.com
      certificate_type: letsencrypt
      api_payload:
        provider: letsencrypt
        dns_challenge: true
      meta:
        managed_by: npmctl
        owner: workload-a
        resource_id: cert.wildcard-example
  accessLists: []
  redirectionHosts: []
  deadHosts: []
  streams: []
  users: []
  settings: []
  dnsRecords: []
  pluginResources: []
  externalCertificates: []
